# Generated by Django 5.1.2 on 2024-12-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('charging_speed', models.CharField(choices=[('fast', 'Fast'), ('slow', 'Slow')], default='slow', max_length=20)),
                ('power_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('connector_types', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('ccs', 'CCS'), ('chademo', 'CHAdeMO')], default='type2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to='myapp.userprofile')),
            ],
        ),
    ]
