# Generated by Django 5.1.4 on 2025-01-05 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="card_last4",
        ),
    ]
