# Generated by Django 5.1.4 on 2025-01-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_chargingstation_availability_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="myapp.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
